[package]
name = "audiveris-image"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
audiveris-core = { path = "../audiveris-core" }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }

[lints]
workspace = true
