[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[dependencies]
audiveris-core = { path = "../crates/audiveris-core" }
audiveris-image = { path = "../crates/audiveris-image" }
audiveris-omr = { path = "../crates/audiveris-omr" }
audiveris-testkit = { path = "../crates/audiveris-testkit" }

[lints]
workspace = true
