#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu
if [ -z "${JAVA_HOME:-}" ] || [ ! -x "$JAVA_HOME/bin/java" ]; then echo "JAVA_HOME must name the frozen Temurin JDK 25" >&2; exit 2; fi
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../../.." && pwd)
tmp_dir=$(mktemp -d /private/tmp/stems-head-phase-bach-s2-q209-audit.XXXXXX)
trap 'rm -rf -- "$tmp_dir"' EXIT
base_probe="$script_dir/StemsHeadPhaseOneBachSystem2Order183Probe.java"; transform="$script_dir/stems-head-phase-bach-system2-order209.transform.awk"; probe="$tmp_dir/StemsHeadPhaseOneBachSystem2Order209Probe.java"; init="$script_dir/stems-head-phase-bach-system2-order209.init.gradle"; input="$repo_root/data/examples/BachInvention5.jpg"
base_runner="$script_dir/run-stems-head-phase-bach-system2-order208.sh"; base_fixture="$repo_root/rust/oracle/stems-head-phase-bach-system2-order208.txt"
base_probe_sha=$(shasum -a 256 "$base_probe"|awk '{print $1}'); base_runner_sha=$(shasum -a 256 "$base_runner"|awk '{print $1}'); base_fixture_sha=$(shasum -a 256 "$base_fixture"|awk '{print $1}')
if [ "$base_probe_sha" != "05c2ff1c14f4f2284ffb80560c82fce4b66c5d41f8debc21e2f5d91fe910a7bb" ] || [ "$base_runner_sha" != "1563fd789415447e97461124a7182c6b45b7213457a8f965038b49a17c9096be" ] || [ "$base_fixture_sha" != "ae7f4b373b81e57d77c9f5733adf8d6c16616f84a88d3161dbd5abdc378d16a2" ]; then echo "strict queue-208 predecessor pins differ" >&2; exit 1; fi
awk -f "$transform" "$base_probe" > "$probe"
run_pass(){ (cd "$repo_root"; env -u JAVA_TOOL_OPTIONS -u _JAVA_OPTIONS -u JDK_JAVA_OPTIONS JAVA_HOME="$JAVA_HOME" ./gradlew --no-daemon -q -Porder209Probe="$probe" -PphaseOneOrder209Page="$input" -I "$init" :app:stemsHeadPhaseBachSystem2Order209Probe) > "$1"; }
run_pass "$tmp_dir/warmup"; run_pass "$tmp_dir/pass1"; run_pass "$tmp_dir/pass2"
grep '^stemsheadbachs2q209' "$tmp_dir/pass1" > "$tmp_dir/rows1"; grep '^stemsheadbachs2q209' "$tmp_dir/pass2" > "$tmp_dir/rows2"; cmp -s "$tmp_dir/rows1" "$tmp_dir/rows2" || { echo "fresh q209 passes differ" >&2; exit 1; }; rows="$tmp_dir/rows1"
if [ "$(grep -c '^stemsheadbachs2q209profile ' "$rows")" -ne 4 ] || [ "$(grep -c '^stemsheadbachs2q209result ' "$rows")" -ne 1 ] || ! grep -q 'stemProfile 0 decisions \[LEFT:top=false:bottom=false:branch=Neither,RIGHT:top=false:bottom=false:branch=Neither\]' "$rows" || ! grep -q 'stemProfile 3 decisions \[LEFT:top=false:bottom=false:branch=Neither,RIGHT:top=false:bottom=false:branch=Neither\]' "$rows" || ! grep -q 'returned false undefs \[\] sideChanges \[x54:sig59:LEFT:false:false->false:true,x54:sig59:RIGHT:false:false->false:true\] incidents \[\]' "$rows" || ! grep -q 'sigVerticesBefore 394 sigVerticesAfter 394 sigEdgesBefore 599 sigEdgesAfter 599 systemStemsBefore 77 systemStemsAfter 77 allocatorUnchanged true nextHeadOrder 210 nextHeadX 48 nextHeadSig 38$' "$rows"; then echo "queue-209 contract differs" >&2; cat "$rows" >&2; exit 1; fi
input_sha=$(shasum -a 256 "$input"|awk '{print $1}'); transform_sha=$(shasum -a 256 "$transform"|awk '{print $1}'); probe_sha=$(shasum -a 256 "$probe"|awk '{print $1}'); init_sha=$(shasum -a 256 "$init"|awk '{print $1}'); runner_sha=$(shasum -a 256 "$0"|awk '{print $1}'); body_sha=$(shasum -a 256 "$rows"|awk '{print $1}'); row_count=$(wc -l < "$rows"|tr -d ' '); out="$repo_root/rust/oracle/stems-head-phase-bach-system2-order209.txt"
{ echo '# Java Audiveris 5.11 Bach system-2 HEADS queue 209 no-link closure.'; echo '# schema: stems-head-phase-bach-system2-order209-v1'; cat "$rows"; printf '%s\n' "stemsheadbachs2q209summary schema stems-head-phase-bach-system2-order209-v1 page BachInvention5.jpg#1 system 2 rows $row_count inputSha256 $input_sha baseProbeSourceSha256 $base_probe_sha transformSourceSha256 $transform_sha transformedProbeSha256 $probe_sha initSourceSha256 $init_sha runnerSourceSha256 $runner_sha emittedBodySha256 $body_sha baseOrder208RunnerSha256 $base_runner_sha baseOrder208FixtureSha256 $base_fixture_sha freshRuns 2 freshRunsByteIdentical true nativeScope FullLifecycleBachSystem2PhaseOneNoLinkClosure javaEvidence ReturnedBeforeHeadOrder210"; } > "$out"
echo "wrote $out"
