#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Deterministic Bach system-2 HEADS queue-205 existing-stem C-link replay.
set -eu
if [ -z "${JAVA_HOME:-}" ] || [ ! -x "$JAVA_HOME/bin/java" ]; then echo "JAVA_HOME must name the frozen Temurin JDK 25" >&2; exit 2; fi
release_field(){ awk -F= -v name="$1" '$1 == name { value=$2; gsub(/^"|"$/, "", value); print value }' "$JAVA_HOME/release"; }
if [ "$(release_field IMPLEMENTOR)" != "Eclipse Adoptium" ] || [ "$(release_field IMPLEMENTOR_VERSION)" != "Temurin-25.0.3+9" ] || [ "$(release_field JAVA_RUNTIME_VERSION)" != "25.0.3+9-LTS" ] || [ "$(release_field OS_NAME)" != "Darwin" ] || [ "$(release_field OS_ARCH)" != "aarch64" ] || [ "$(release_field JVM_VARIANT)" != "Hotspot" ]; then echo "JAVA_HOME is not frozen Temurin 25.0.3+9-LTS aarch64 HotSpot" >&2; exit 2; fi
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../../.." && pwd)
tmp_dir=$(mktemp -d /private/tmp/stems-head-phase-bach-s2-q205.XXXXXX)
trap 'rm -rf -- "$tmp_dir"' EXIT
base_probe="$script_dir/StemsHeadMultiBeamCLinkPageProbe.java"; transform="$script_dir/stems-head-phase-bach-system2-order205.transform.awk"; probe="$tmp_dir/StemsHeadBachSystem2Order205CLinkProbe.java"; init="$script_dir/stems-head-phase-bach-system2-order205.init.gradle"; input="$repo_root/data/examples/BachInvention5.jpg"
base_runner="$script_dir/run-stems-head-phase-bach-system2-order204.sh"; base_fixture="$repo_root/rust/oracle/stems-head-phase-bach-system2-order204.txt"
base_probe_sha=$(shasum -a 256 "$base_probe"|awk '{print $1}'); base_runner_sha=$(shasum -a 256 "$base_runner"|awk '{print $1}'); base_fixture_sha=$(shasum -a 256 "$base_fixture"|awk '{print $1}')
if [ "$base_probe_sha" != "72e85d0de1838664db221fa890917b83a1140bf6ee5ea99b0a1f6bc1839fec33" ] || [ "$base_runner_sha" != "b163837cc4257da17a39aeeb4ae5943369c406b474dbd0ae1a05119f72883db3" ] || [ "$base_fixture_sha" != "d3d4f40f096cc0bb0a47a32b9a54d91e46b0bde1faf05a58e2484b8504ac8703" ]; then echo "strict queue-204 predecessor pins differ" >&2; exit 1; fi
awk -f "$transform" "$base_probe" > "$probe"
run_pass(){ (cd "$repo_root"; env -u JAVA_TOOL_OPTIONS -u _JAVA_OPTIONS -u JDK_JAVA_OPTIONS JAVA_HOME="$JAVA_HOME" ./gradlew --no-daemon -q -Porder205Probe="$probe" -Porder205Page="$input" -I "$init" :app:stemsHeadBachSystem2Order205CLinkProbe) > "$1"; }
run_pass "$tmp_dir/warmup"; run_pass "$tmp_dir/pass1"; run_pass "$tmp_dir/pass2"
grep '^stemsheadbachs2q205' "$tmp_dir/pass1" > "$tmp_dir/rows1"; grep '^stemsheadbachs2q205' "$tmp_dir/pass2" > "$tmp_dir/rows2"; cmp -s "$tmp_dir/rows1" "$tmp_dir/rows2" || { echo "fresh queue-205 passes differ" >&2; exit 1; }; rows="$tmp_dir/rows1"
if [ "$(grep -c '^stemsheadbachs2q205frontier ' "$rows")" -ne 1 ] || [ "$(grep -c '^stemsheadbachs2q205result ' "$rows")" -ne 1 ] || ! grep -q 'headOrder 205 headX 24 headSig 210 headInterId 4030 .*cAlias h:24:RIGHT:BOTTOM .*lastIndex 1 maxIndex 1' "$rows" || ! grep -q 'relations 1 .*glyphs 2 selected \[candidateGlyph:g:416:875:6:59:eb8ca47e5bce63b84f34a4784f90841658c09884d4aa0dc4170511b87edf2632,supportGlyph:g:418:875:3:59:517dfad97f01f1b18d863b2606e467044d33bfc9268b4aac811a735274552c8c\]' "$rows" || ! grep -q 'candidateIdBefore 0 .*existingCandidateStem true .*existingBeamRelations \[\].*terminal ReadyForMultiBeamCLink$' "$rows" || ! grep -q '^stemsheadbachs2q205result .*returned true undefs \[\] allocatorDelta 0 sigVerticesBefore 394 sigVerticesAfter 394 sigEdgesBefore 598 sigEdgesAfter 599 systemStemsBefore 77 systemStemsAfter 77 addedVertices \[\] addedEdges \[source=headX24:target=existingCandidateStem:HeadStemRelation' "$rows" || ! grep -q 'addedSystemStems \[\].*nextHeadOrder 206 nextHeadX 118 nextHeadSig 211 nextHeadInterId 4031 terminal ReturnedMultiBeamCLinkTransaction$' "$rows"; then echo "Bach system-2 queue-205 contract differs" >&2; cat "$rows" >&2; exit 1; fi
input_sha=$(shasum -a 256 "$input"|awk '{print $1}'); transform_sha=$(shasum -a 256 "$transform"|awk '{print $1}'); probe_sha=$(shasum -a 256 "$probe"|awk '{print $1}'); init_sha=$(shasum -a 256 "$init"|awk '{print $1}'); runner_sha=$(shasum -a 256 "$0"|awk '{print $1}'); body_sha=$(shasum -a 256 "$rows"|awk '{print $1}'); row_count=$(wc -l < "$rows"|tr -d ' '); out="$repo_root/rust/oracle/stems-head-phase-bach-system2-order205.txt"
{ echo '# Java Audiveris 5.11 (Temurin JDK 25.0.3+9 LTS) Bach system-2 HEADS queue 205 existing-stem two-item C-link.'; echo '# schema: stems-head-phase-bach-system2-order205-v1'; cat "$rows"; printf '%s\n' "stemsheadbachs2q205summary schema stems-head-phase-bach-system2-order205-v1 page BachInvention5.jpg#1 system 2 rows $row_count inputSha256 $input_sha baseProbeSourceSha256 $base_probe_sha transformSourceSha256 $transform_sha transformedProbeSha256 $probe_sha initSourceSha256 $init_sha runnerSourceSha256 $runner_sha emittedBodySha256 $body_sha baseOrder204RunnerSha256 $base_runner_sha baseOrder204FixtureSha256 $base_fixture_sha freshRuns 2 freshRunsByteIdentical true nativeScope FullLifecycleBachSystem2PhaseOneExistingStemTwoItemCLink javaEvidence ReturnedBeforeHeadOrder206"; } > "$out"
echo "wrote $out"
