#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu
if [ -z "${JAVA_HOME:-}" ] || [ ! -x "$JAVA_HOME/bin/java" ]; then echo "JAVA_HOME must name the frozen Temurin JDK 25" >&2; exit 2; fi
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../../.." && pwd)
tmp_dir=$(mktemp -d /private/tmp/stems-head-phase-bach-s2-q208.XXXXXX)
trap 'rm -rf -- "$tmp_dir"' EXIT
base_probe="$script_dir/StemsHeadPhaseOneBachSystem2Order183Probe.java"; transform="$script_dir/stems-head-phase-bach-system2-order208.transform.awk"; probe="$tmp_dir/StemsHeadPhaseOneBachSystem2Order208Probe.java"; init="$script_dir/stems-head-phase-bach-system2-order208.init.gradle"; input="$repo_root/data/examples/BachInvention5.jpg"
base_runner="$script_dir/run-stems-head-phase-bach-system2-order207.sh"; base_fixture="$repo_root/rust/oracle/stems-head-phase-bach-system2-order207.txt"
base_probe_sha=$(shasum -a 256 "$base_probe"|awk '{print $1}'); base_runner_sha=$(shasum -a 256 "$base_runner"|awk '{print $1}'); base_fixture_sha=$(shasum -a 256 "$base_fixture"|awk '{print $1}')
if [ "$base_probe_sha" != "05c2ff1c14f4f2284ffb80560c82fce4b66c5d41f8debc21e2f5d91fe910a7bb" ] || [ "$base_runner_sha" != "167b9f622b17073f9312344d7d18e8c7fbac47bf72522ee8481f71fe3540d8fe" ] || [ "$base_fixture_sha" != "fa4a841724272faf3633f5f703114efc2f9021700a07d0cd1105eacad39ce74c" ]; then echo "strict queue-207 predecessor pins differ" >&2; exit 1; fi
awk -f "$transform" "$base_probe" > "$probe"
run_pass(){ (cd "$repo_root"; env -u JAVA_TOOL_OPTIONS -u _JAVA_OPTIONS -u JDK_JAVA_OPTIONS JAVA_HOME="$JAVA_HOME" ./gradlew --no-daemon -q -Porder208Probe="$probe" -PphaseOneOrder208Page="$input" -I "$init" :app:stemsHeadPhaseBachSystem2Order208Probe) > "$1"; }
run_pass "$tmp_dir/warmup"; run_pass "$tmp_dir/pass1"; run_pass "$tmp_dir/pass2"
grep '^stemsheadbachs2q208' "$tmp_dir/pass1" > "$tmp_dir/rows1"; grep '^stemsheadbachs2q208' "$tmp_dir/pass2" > "$tmp_dir/rows2"; cmp -s "$tmp_dir/rows1" "$tmp_dir/rows2" || { echo "fresh q208 passes differ" >&2; exit 1; }; rows="$tmp_dir/rows1"
if [ "$(grep -c '^stemsheadbachs2q208profile ' "$rows")" -ne 4 ] || [ "$(grep -c '^stemsheadbachs2q208result ' "$rows")" -ne 1 ] || ! grep -q 'stemProfile 0 decisions \[LEFT:SkipClosed,RIGHT:SkipAlreadyLinked\]' "$rows" || ! grep -q 'stemProfile 3 decisions \[LEFT:SkipClosed,RIGHT:SkipAlreadyLinked\]' "$rows" || ! grep -q 'returned true undefs \[\] sideChanges \[x56:sig60:LEFT:false:false->false:true,x56:sig60:RIGHT:true:false->true:true\] incidents \[existingStem:headSideRIGHT:heads\[x55:sig67:sideRIGHT,x56:sig60:sideRIGHT\]\]' "$rows" || ! grep -q 'sigVerticesBefore 394 sigVerticesAfter 394 sigEdgesBefore 599 sigEdgesAfter 599 systemStemsBefore 77 systemStemsAfter 77 allocatorUnchanged true nextHeadOrder 209 nextHeadX 54 nextHeadSig 59$' "$rows"; then echo "queue-208 contract differs" >&2; cat "$rows" >&2; exit 1; fi
input_sha=$(shasum -a 256 "$input"|awk '{print $1}'); transform_sha=$(shasum -a 256 "$transform"|awk '{print $1}'); probe_sha=$(shasum -a 256 "$probe"|awk '{print $1}'); init_sha=$(shasum -a 256 "$init"|awk '{print $1}'); runner_sha=$(shasum -a 256 "$0"|awk '{print $1}'); body_sha=$(shasum -a 256 "$rows"|awk '{print $1}'); row_count=$(wc -l < "$rows"|tr -d ' '); out="$repo_root/rust/oracle/stems-head-phase-bach-system2-order208.txt"
{ echo '# Java Audiveris 5.11 Bach system-2 HEADS queue 208 right-side two-head reconciliation.'; echo '# schema: stems-head-phase-bach-system2-order208-v1'; cat "$rows"; printf '%s\n' "stemsheadbachs2q208summary schema stems-head-phase-bach-system2-order208-v1 page BachInvention5.jpg#1 system 2 rows $row_count inputSha256 $input_sha baseProbeSourceSha256 $base_probe_sha transformSourceSha256 $transform_sha transformedProbeSha256 $probe_sha initSourceSha256 $init_sha runnerSourceSha256 $runner_sha emittedBodySha256 $body_sha baseOrder207RunnerSha256 $base_runner_sha baseOrder207FixtureSha256 $base_fixture_sha freshRuns 2 freshRunsByteIdentical true nativeScope FullLifecycleBachSystem2PhaseOneRightSideTwoHeadReconciliation javaEvidence ReturnedBeforeHeadOrder209"; } > "$out"
echo "wrote $out"
