#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu
if [ -z "${JAVA_HOME:-}" ] || [ ! -x "$JAVA_HOME/bin/java" ]; then echo "JAVA_HOME must name the frozen Temurin JDK 25" >&2; exit 2; fi
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../../.." && pwd)
tmp_dir=$(mktemp -d /private/tmp/stems-head-phase-bach-s2-q212-audit.XXXXXX)
trap 'rm -rf -- "$tmp_dir"' EXIT
base_probe="$script_dir/StemsHeadPhaseOneBachSystem2Order183Probe.java"; transform="$script_dir/stems-head-phase-bach-system2-order212.transform.awk"; probe="$tmp_dir/StemsHeadPhaseOneBachSystem2Order212Probe.java"; init="$script_dir/stems-head-phase-bach-system2-order212.init.gradle"; input="$repo_root/data/examples/BachInvention5.jpg"
base_runner="$script_dir/run-stems-head-phase-bach-system2-order211.sh"; base_fixture="$repo_root/rust/oracle/stems-head-phase-bach-system2-order211.txt"
base_probe_sha=$(shasum -a 256 "$base_probe"|awk '{print $1}'); base_runner_sha=$(shasum -a 256 "$base_runner"|awk '{print $1}'); base_fixture_sha=$(shasum -a 256 "$base_fixture"|awk '{print $1}')
if [ "$base_probe_sha" != "05c2ff1c14f4f2284ffb80560c82fce4b66c5d41f8debc21e2f5d91fe910a7bb" ] || [ "$base_runner_sha" != "1a7c5eb47453b364a32a030250be5b553b869410b631e4bdd5889570c7330ba3" ] || [ "$base_fixture_sha" != "c2eb23f0ed638111810c27421e014d262d05c9e2fd9cc53f3ece4f0a607ad980" ]; then echo "strict queue-211 predecessor pins differ" >&2; exit 1; fi
awk -f "$transform" "$base_probe" > "$probe"
run_pass(){ (cd "$repo_root"; env -u JAVA_TOOL_OPTIONS -u _JAVA_OPTIONS -u JDK_JAVA_OPTIONS JAVA_HOME="$JAVA_HOME" ./gradlew --no-daemon -q -Porder212Probe="$probe" -PphaseOneOrder212Page="$input" -I "$init" :app:stemsHeadPhaseBachSystem2Order212Probe) > "$1"; }
run_pass "$tmp_dir/warmup"; run_pass "$tmp_dir/pass1"; run_pass "$tmp_dir/pass2"
grep '^stemsheadbachs2q212' "$tmp_dir/pass1" > "$tmp_dir/rows1"; grep '^stemsheadbachs2q212' "$tmp_dir/pass2" > "$tmp_dir/rows2"; cmp -s "$tmp_dir/rows1" "$tmp_dir/rows2" || { echo "fresh q212 passes differ" >&2; exit 1; }; rows="$tmp_dir/rows1"
if [ "$(grep -c '^stemsheadbachs2q212profile ' "$rows")" -ne 4 ] || [ "$(grep -c '^stemsheadbachs2q212result ' "$rows")" -ne 1 ] || ! grep -q 'stemProfile 0 decisions \[LEFT:SkipAlreadyLinked,RIGHT:SkipClosed\]' "$rows" || ! grep -q 'stemProfile 3 decisions \[LEFT:SkipAlreadyLinked,RIGHT:SkipClosed\]' "$rows" || ! grep -q 'returned true undefs \[\] sideChanges \[\] incidents \[existingStem:headSideLEFT:heads\[x110:sig158:sideRIGHT,x112:sig122:sideLEFT,x113:sig106:sideLEFT,x114:sig107:sideLEFT,x116:sig202:sideLEFT\]\]' "$rows" || ! grep -q 'sigVerticesBefore 394 sigVerticesAfter 394 sigEdgesBefore 599 sigEdgesAfter 599 systemStemsBefore 77 systemStemsAfter 77 allocatorUnchanged true nextHeadOrder 213 nextHeadX 29 nextHeadSig 92$' "$rows"; then echo "queue-212 contract differs" >&2; cat "$rows" >&2; exit 1; fi
input_sha=$(shasum -a 256 "$input"|awk '{print $1}'); transform_sha=$(shasum -a 256 "$transform"|awk '{print $1}'); probe_sha=$(shasum -a 256 "$probe"|awk '{print $1}'); init_sha=$(shasum -a 256 "$init"|awk '{print $1}'); runner_sha=$(shasum -a 256 "$0"|awk '{print $1}'); body_sha=$(shasum -a 256 "$rows"|awk '{print $1}'); row_count=$(wc -l < "$rows"|tr -d ' '); out="$repo_root/rust/oracle/stems-head-phase-bach-system2-order212.txt"
{ echo '# Java Audiveris 5.11 Bach system-2 HEADS queue 212 mixed-side five-head zero-change reconciliation.'; echo '# schema: stems-head-phase-bach-system2-order212-v1'; cat "$rows"; printf '%s\n' "stemsheadbachs2q212summary schema stems-head-phase-bach-system2-order212-v1 page BachInvention5.jpg#1 system 2 rows $row_count inputSha256 $input_sha baseProbeSourceSha256 $base_probe_sha transformSourceSha256 $transform_sha transformedProbeSha256 $probe_sha initSourceSha256 $init_sha runnerSourceSha256 $runner_sha emittedBodySha256 $body_sha baseOrder211RunnerSha256 $base_runner_sha baseOrder211FixtureSha256 $base_fixture_sha freshRuns 2 freshRunsByteIdentical true nativeScope FullLifecycleBachSystem2PhaseOneMixedSideFiveHeadZeroChangeReconciliation javaEvidence ReturnedBeforeHeadOrder213"; } > "$out"
echo "wrote $out"
