#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu
if [ -z "${JAVA_HOME:-}" ] || [ ! -x "$JAVA_HOME/bin/java" ]; then echo "JAVA_HOME must name the frozen Temurin JDK 25" >&2; exit 2; fi
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../../.." && pwd)
tmp_dir=$(mktemp -d /private/tmp/stems-head-phase-bach-s2-q207.XXXXXX)
trap 'rm -rf -- "$tmp_dir"' EXIT
base_probe="$script_dir/StemsHeadPhaseOneBachSystem2Order183Probe.java"; transform="$script_dir/stems-head-phase-bach-system2-order207.transform.awk"; probe="$tmp_dir/StemsHeadPhaseOneBachSystem2Order207Probe.java"; init="$script_dir/stems-head-phase-bach-system2-order207.init.gradle"; input="$repo_root/data/examples/BachInvention5.jpg"
base_runner="$script_dir/run-stems-head-phase-bach-system2-order206.sh"; base_fixture="$repo_root/rust/oracle/stems-head-phase-bach-system2-order206.txt"
base_probe_sha=$(shasum -a 256 "$base_probe"|awk '{print $1}'); base_runner_sha=$(shasum -a 256 "$base_runner"|awk '{print $1}'); base_fixture_sha=$(shasum -a 256 "$base_fixture"|awk '{print $1}')
if [ "$base_probe_sha" != "05c2ff1c14f4f2284ffb80560c82fce4b66c5d41f8debc21e2f5d91fe910a7bb" ] || [ "$base_runner_sha" != "f8a9cf2042a9e19204c4c5305eb7bd95d21f20eb08773d1214284abdce3b9d20" ] || [ "$base_fixture_sha" != "5f2ecd4cd42c8182b13ac560db4447682fe130b2587ce8a66844c4253bae5bab" ]; then echo "strict queue-206 predecessor pins differ" >&2; exit 1; fi
awk -f "$transform" "$base_probe" > "$probe"
run_pass(){ (cd "$repo_root"; env -u JAVA_TOOL_OPTIONS -u _JAVA_OPTIONS -u JDK_JAVA_OPTIONS JAVA_HOME="$JAVA_HOME" ./gradlew --no-daemon -q -Porder207Probe="$probe" -PphaseOneOrder207Page="$input" -I "$init" :app:stemsHeadPhaseBachSystem2Order207Probe) > "$1"; }
run_pass "$tmp_dir/warmup"; run_pass "$tmp_dir/pass1"; run_pass "$tmp_dir/pass2"
grep '^stemsheadbachs2q207' "$tmp_dir/pass1" > "$tmp_dir/rows1"; grep '^stemsheadbachs2q207' "$tmp_dir/pass2" > "$tmp_dir/rows2"; cmp -s "$tmp_dir/rows1" "$tmp_dir/rows2" || { echo "fresh q207 passes differ" >&2; exit 1; }; rows="$tmp_dir/rows1"
if [ "$(grep -c '^stemsheadbachs2q207profile ' "$rows")" -ne 4 ] || [ "$(grep -c '^stemsheadbachs2q207result ' "$rows")" -ne 1 ] || ! grep -q 'stemProfile 0 decisions \[LEFT:SkipClosed,RIGHT:SkipAlreadyLinked\]' "$rows" || ! grep -q 'stemProfile 3 decisions \[LEFT:SkipClosed,RIGHT:SkipAlreadyLinked\]' "$rows" || ! grep -q 'returned true undefs \[\] sideChanges \[x161:sig212:LEFT:true:false->true:true,x161:sig212:RIGHT:true:false->true:true\] incidents \[existingStem:headSideRIGHT:heads\[x153:sig162:sideRIGHT,x154:sig163:sideRIGHT,x156:sig159:sideRIGHT,x161:sig212:sideLEFT\]\]' "$rows" || ! grep -q 'sigVerticesBefore 394 sigVerticesAfter 394 sigEdgesBefore 599 sigEdgesAfter 599 systemStemsBefore 77 systemStemsAfter 77 allocatorUnchanged true nextHeadOrder 208 nextHeadX 55 nextHeadSig 67$' "$rows"; then echo "queue-207 contract differs" >&2; cat "$rows" >&2; exit 1; fi
input_sha=$(shasum -a 256 "$input"|awk '{print $1}'); transform_sha=$(shasum -a 256 "$transform"|awk '{print $1}'); probe_sha=$(shasum -a 256 "$probe"|awk '{print $1}'); init_sha=$(shasum -a 256 "$init"|awk '{print $1}'); runner_sha=$(shasum -a 256 "$0"|awk '{print $1}'); body_sha=$(shasum -a 256 "$rows"|awk '{print $1}'); row_count=$(wc -l < "$rows"|tr -d ' '); out="$repo_root/rust/oracle/stems-head-phase-bach-system2-order207.txt"
{ echo '# Java Audiveris 5.11 Bach system-2 HEADS queue 207 right-side four-head reconciliation.'; echo '# schema: stems-head-phase-bach-system2-order207-v1'; cat "$rows"; printf '%s\n' "stemsheadbachs2q207summary schema stems-head-phase-bach-system2-order207-v1 page BachInvention5.jpg#1 system 2 rows $row_count inputSha256 $input_sha baseProbeSourceSha256 $base_probe_sha transformSourceSha256 $transform_sha transformedProbeSha256 $probe_sha initSourceSha256 $init_sha runnerSourceSha256 $runner_sha emittedBodySha256 $body_sha baseOrder206RunnerSha256 $base_runner_sha baseOrder206FixtureSha256 $base_fixture_sha freshRuns 2 freshRunsByteIdentical true nativeScope FullLifecycleBachSystem2PhaseOneRightSideFourHeadReconciliation javaEvidence ReturnedBeforeHeadOrder208"; } > "$out"
echo "wrote $out"
