// SPDX-License-Identifier: AGPL-3.0-or-later
//! Boundary 20: the second frontier's transaction, replayed through the
//! production chain at the position Boundary 19 proved.
//!
//! Fast evidence per `rust/PORTING.md`: the frozen per-family txn2 fixtures
//! were generated by a probe whose fresh emitters reproduced the frozen
//! first-transaction rows byte-for-byte in the same run (replay-on-frozen),
//! and whose txn1 head/outer/resume row subsequences matched their frozen
//! fixtures before anything was written.  This gate patches the native
//! scheduler to the Boundary-19 second frontier, feeds the txn2 texts into
//! the same hydration `run_real` uses, and replays boundaries 12 through 15
//! plus the Boundary-18 outer assignment with the production functions.  The
//! Boundary-16/17 typed replay at this frontier is owed at the next full
//! checkpoint; their txn2 fixtures are pinned here by count and hash.

#[path = "common/b15_hydration.rs"]
mod b15_hydration;

use std::path::PathBuf;

use audiveris_omr::native_stems_beam_scheduler::{
    NativeStemsBeamCompletedVLinkEvidence, NativeStemsBeamSchedulerResumeStatus,
    NativeStemsBeamSchedulerStatus, resume_native_stems_beam_scheduler_after_transaction,
};
use audiveris_omr::native_stems_beam_vlink_outer_b_linker::{
    NativeStemsBeamOuterBLinkerCell, NativeStemsBeamOuterVLinkerFact,
    apply_native_stems_beam_vlink_outer_b_linker_transaction,
};
/// The beam corpus in its usual order. The gate grades every sheet whose
/// fixtures are installed and tolerates a gap only at the end, so a sheet that
/// is frozen but ungraded cannot hide between two graded ones.
const PAGES: [(&str, &str, usize); 8] = [
    ("chula", "chula.png", 3),
    ("allegretto", "allegretto.png", 3),
    ("batuque", "batuque.png", 3),
    ("carmen", "carmen.png", 5),
    ("cucaracha", "cucaracha.png", 3),
    ("hove", "hove.png", 5),
    ("zizi", "zizi.png", 2),
    ("BachInvention5", "BachInvention5.jpg", 6),
];

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn sha256_hex(bytes: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut padded = bytes.to_vec();
    let bit_len = u64::try_from(bytes.len()).expect("fixture length fits u64") * 8;
    padded.push(0x80);
    while padded.len() % 64 != 56 {
        padded.push(0);
    }
    padded.extend_from_slice(&bit_len.to_be_bytes());
    let mut state = [
        0x6a09e667_u32,
        0xbb67ae85,
        0x3c6ef372,
        0xa54ff53a,
        0x510e527f,
        0x9b05688c,
        0x1f83d9ab,
        0x5be0cd19,
    ];
    for chunk in padded.chunks_exact(64) {
        let mut words = [0_u32; 64];
        for (index, word) in words[..16].iter_mut().enumerate() {
            let offset = index * 4;
            *word = u32::from_be_bytes([
                chunk[offset],
                chunk[offset + 1],
                chunk[offset + 2],
                chunk[offset + 3],
            ]);
        }
        for index in 16..64 {
            let s0 = words[index - 15].rotate_right(7)
                ^ words[index - 15].rotate_right(18)
                ^ (words[index - 15] >> 3);
            let s1 = words[index - 2].rotate_right(17)
                ^ words[index - 2].rotate_right(19)
                ^ (words[index - 2] >> 10);
            words[index] = words[index - 16]
                .wrapping_add(s0)
                .wrapping_add(words[index - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = state;
        for index in 0..64 {
            let sigma1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let choice = (e & f) ^ ((!e) & g);
            let temporary1 = h
                .wrapping_add(sigma1)
                .wrapping_add(choice)
                .wrapping_add(K[index])
                .wrapping_add(words[index]);
            let sigma0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let majority = (a & b) ^ (a & c) ^ (b & c);
            let temporary2 = sigma0.wrapping_add(majority);
            h = g;
            g = f;
            f = e;
            e = d.wrapping_add(temporary1);
            d = c;
            c = b;
            b = a;
            a = temporary1.wrapping_add(temporary2);
        }
        for (slot, value) in state.iter_mut().zip([a, b, c, d, e, f, g, h]) {
            *slot = slot.wrapping_add(value);
        }
    }
    state.iter().map(|word| format!("{word:08x}")).collect()
}

fn txn2_text(family: &str, key: &str) -> String {
    let path = repo_root().join(format!("rust/oracle/stems-beam-txn2-{family}-{key}.txt"));
    std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()))
}

fn row_field<'a>(row: &'a str, name: &str) -> &'a str {
    let mut tokens = row.split(' ');
    while let Some(token) = tokens.next() {
        if token == name {
            return tokens
                .next()
                .unwrap_or_else(|| panic!("field {name} lacks a value: {row}"));
        }
    }
    panic!("row lacks {name}: {row}");
}

fn family_rows<'a>(text: &'a str, family: &str, system_id: usize) -> Vec<&'a str> {
    let marker = format!(" system {system_id} ");
    text.lines()
        .filter(|line| line.split(' ').next() == Some(family) && line.contains(&marker))
        .collect()
}

#[test]
fn second_transaction_replays_through_production_chain() {
    let mut graded = 0;
    let mut saw_missing = false;
    for (key, image, expected_systems) in PAGES {
        let manifest_path =
            repo_root().join(format!("rust/oracle/stems-beam-txn2-manifest-{key}.txt"));
        if !manifest_path.is_file() {
            saw_missing = true;
            continue;
        }
        assert!(
            !saw_missing,
            "installed Boundary-20 corpus has a gap before {key}"
        );
        let manifest = txn2_text("manifest", key);
        let resume_fixture_path =
            repo_root().join(format!("rust/oracle/stems-beam-scheduler-resume-{key}.txt"));
        let resume_bytes = std::fs::read(&resume_fixture_path)
            .unwrap_or_else(|error| panic!("cannot read boundary-19 fixture: {error}"));
        let page_row = manifest
            .lines()
            .find(|line| line.starts_with("stemsbeamtxn2page "))
            .unwrap_or_else(|| panic!("{key}: manifest lacks its page row"));
        assert_eq!(
            row_field(page_row, "schedulerResumeFixtureSha256"),
            sha256_hex(&resume_bytes),
            "{key}: manifest does not pin its exact boundary-19 fixture"
        );
        assert_eq!(
            row_field(page_row, "stop"),
            "SecondTransactionOuterAssignmentComplete"
        );
        assert_eq!(
            row_field(page_row, "systems").parse::<usize>().unwrap(),
            expected_systems
        );

        let base_text = txn2_text("base-apply", key);
        let create_text = txn2_text("create-stem", key);
        let reuse_text = txn2_text("reuse-check", key);
        let flag_text = txn2_text("b-linker-flag", key);
        let sibling_text = txn2_text("sibling-links", key);
        let head_text = txn2_text("head-links", key);
        let outer_text = txn2_text("outer-blinker", key);

        let mut page = b15_hydration::native_predecessor_page(image);
        for index in 0..page.scheduler.systems.len() {
            let scheduler_system = &page.scheduler.systems[index];
            let system_id = scheduler_system.system_id;
            let NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(first) =
                &scheduler_system.status
            else {
                panic!("{key} system {system_id}: prefix lacks its first frontier");
            };
            let completed = NativeStemsBeamCompletedVLinkEvidence {
                plan: first.plan,
                b_linker: first.b_linker,
                v_linker: first.v_linker,
                outer_b_linked_after: true,
            };
            let resume = resume_native_stems_beam_scheduler_after_transaction(
                scheduler_system,
                &page.beam_vlinkers.systems[index],
                &page.beam_builders.systems[index],
                &page.plans.systems[index],
                &completed,
            )
            .unwrap_or_else(|error| panic!("{key} system {system_id}: resume failed: {error}"));
            let NativeStemsBeamSchedulerResumeStatus::AwaitingVLinkTransaction(second) =
                resume.status
            else {
                panic!("{key} system {system_id}: resume did not reach a second frontier");
            };
            // The create-state builder refuses committed prefix deltas; the fast
            // corpus resume adds none, asserted here so a future page cannot
            // silently violate the assumption.
            assert!(
                page.scheduler.systems[index]
                    .deferred_line_deltas
                    .is_empty(),
                "{key} system {system_id}: prefix deltas unsupported at txn2"
            );
            page.scheduler.systems[index].status =
                NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(second);
        }

        for index in 0..page.scheduler.systems.len() {
            let system_id = page.scheduler.systems[index].system_id;
            let NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(second) =
                &page.scheduler.systems[index].status
            else {
                unreachable!();
            };
            let second = second.as_ref().clone();

            // Boundaries 12-15 at the second frontier, through the production
            // applies and the txn2 evidence, exactly as run_real does at the
            // first frontier.
            let hydrated = b15_hydration::run_real_on_page(
                &page,
                system_id,
                &base_text,
                &create_text,
                &reuse_text,
                false,
            )
            .unwrap_or_else(|error| {
                panic!("{key} system {system_id}: txn2 boundary 12-15 replay failed: {error}")
            });
            assert_eq!(hydrated.transaction.key.plan, second.plan);
            assert!(hydrated.transaction.linked_after);
            assert!(!hydrated.transaction.linked_before);
            assert_eq!(hydrated.target, second.b_linker);
            assert_eq!(hydrated.triggering, second.v_linker);

            // Boundary 18 at the second frontier.
            let mut cell = NativeStemsBeamOuterBLinkerCell {
                target_b_linker: hydrated.target,
                linked: hydrated.state_after.linked,
                closed: false,
                committed_by_flag_boundary: hydrated.state_after.committed,
            };
            let facts = hydrated
                .ordered_observers
                .iter()
                .map(|observer| {
                    assert_eq!(
                        *observer, hydrated.triggering,
                        "{key} system {system_id}: non-current observer needs a target fact"
                    );
                    NativeStemsBeamOuterVLinkerFact {
                        v_linker: *observer,
                        has_target_linkers: true,
                    }
                })
                .collect::<Vec<_>>();
            let outer = apply_native_stems_beam_vlink_outer_b_linker_transaction(
                hydrated.transaction.key,
                true,
                hydrated.triggering,
                &facts,
                &mut cell,
            )
            .unwrap_or_else(|error| {
                panic!("{key} system {system_id}: txn2 boundary-18 apply failed: {error}")
            });
            let outer_rows = family_rows(&outer_text, "stemsbeamvlinkouterblinker", system_id);
            assert_eq!(
                outer_rows.len(),
                1,
                "{key} system {system_id}: expected one txn2 outer row"
            );
            let outer_row = outer_rows[0];
            assert_eq!(
                row_field(outer_row, "plan").parse::<usize>().unwrap(),
                second.plan.plan_ordinal
            );
            assert_eq!(row_field(outer_row, "linkedBefore"), "true");
            assert_eq!(
                row_field(outer_row, "valueChanged") == "true",
                outer.linked_value_change_count > 0
            );
            assert_eq!(
                row_field(outer_row, "vSide"),
                match outer.current_v_linker.side {
                    audiveris_omr::stems_step::NativeStemVerticalSide::Top => "TOP",
                    audiveris_omr::stems_step::NativeStemVerticalSide::Bottom => "BOTTOM",
                },
            );
            assert_eq!(outer.linked_write_count, 1);
            assert!(cell.linked);

            // Boundary 16/17 txn2 evidence: pinned by structure now, typed
            // replay owed at the next full checkpoint.
            let flag_targets =
                family_rows(&flag_text, "stemsbeamvlinkblinkerflagtarget", system_id);
            assert_eq!(flag_targets.len(), 1);
            assert_eq!(
                row_field(flag_targets[0], "plan").parse::<usize>().unwrap(),
                second.plan.plan_ordinal
            );
            assert_eq!(row_field(flag_targets[0], "linkedBefore"), "false");
            assert_eq!(row_field(flag_targets[0], "linkedAfter"), "true");
            let head_predecessors =
                family_rows(&head_text, "stemsbeamvlinkheadlinkspredecessor", system_id);
            assert_eq!(head_predecessors.len(), 1);
            let sibling_rows = sibling_text
                .lines()
                .filter(|line| {
                    line.starts_with("stemsbeamvlinksiblinglinks")
                        && line.contains(&format!(" system {system_id} "))
                })
                .count();
            assert_eq!(
                row_field(head_predecessors[0], "b16TransactionRows")
                    .parse::<usize>()
                    .unwrap(),
                sibling_rows,
                "{key} system {system_id}: head predecessor row must pin the sibling bundle"
            );
        }
        graded += 1;
    }
    // Count what is on disk rather than trusting a floor: a gate that grades
    // two sheets of eight would satisfy `>= 2` while quietly ignoring six.
    let installed = PAGES
        .iter()
        .filter(|(key, _, _)| {
            repo_root()
                .join(format!("rust/oracle/stems-beam-txn2-manifest-{key}.txt"))
                .is_file()
        })
        .count();
    assert!(
        installed >= 2,
        "Boundary-20 has only {installed} sheets frozen"
    );
    assert_eq!(
        graded, installed,
        "Boundary-20 graded {graded} of {installed} installed sheets"
    );
}
