// SPDX-License-Identifier: AGPL-3.0-or-later
//! Boundary 20: the second frontier's transaction, replayed through the
//! production chain at the position Boundary 19 proved.
//!
//! Fast evidence per `rust/PORTING.md`: the frozen per-family txn2 fixtures
//! were generated by a probe whose fresh emitters reproduced the frozen
//! first-transaction rows byte-for-byte in the same run (replay-on-frozen),
//! and whose txn1 head/outer/resume row subsequences matched their frozen
//! fixtures before anything was written.  This gate patches the native
//! scheduler to the Boundary-19 second frontier, feeds the txn2 texts into
//! the same hydration `run_real` uses, and replays boundaries 12 through 15
//! plus the Boundary-18 outer assignment with the production functions.  The
//! Boundary-16/17 typed replay at this frontier is owed at the next full
//! checkpoint; their txn2 fixtures are pinned here by count and hash.

#[path = "common/b15_hydration.rs"]
mod b15_hydration;

use std::path::PathBuf;

use audiveris_omr::native_stems_beam_scheduler::{
    NativeStemsBeamCompletedVLinkEvidence, NativeStemsBeamSchedulerResumeStatus,
    NativeStemsBeamSchedulerStatus, resume_native_stems_beam_scheduler_after_transaction,
};
use audiveris_omr::native_stems_beam_vlink_head_links::initialize_native_stems_beam_s_linker_cells;
use audiveris_omr::native_stems_beam_vlink_outer_b_linker::{
    NativeStemsBeamOuterBLinkerCell, NativeStemsBeamOuterVLinkerFact,
    apply_native_stems_beam_vlink_outer_b_linker_transaction,
};
use audiveris_omr::native_stems_beam_vlink_reuse_check::{
    NativeStemsBeamReuseDisposition, NativeStemsBeamReuseEntryObservation,
    NativeStemsBeamVLinkReuseCheckOutcome, NativeStemsBeamVLinkReuseLiveEvaluation,
    evaluate_native_stems_beam_vlink_reuse_check, project_native_stems_beam_vlink_reuse_live_state,
};
use audiveris_omr::native_stems_beam_vlink_transaction::{
    NativeStemsBeamCreateStemDisposition, NativeStemsBeamFixedGlyphContent,
    NativeStemsBeamGlyphRegistrationAction, NativeStemsBeamGlyphRegistryBootstrapEntry,
    NativeStemsBeamSystemStemAuthorityProof, apply_native_stems_beam_vlink_create_stem_transaction,
    prepare_native_stems_beam_vlink_frontier_state,
};
/// The beam corpus in its usual order. The gate grades every sheet whose
/// fixtures are installed and tolerates a gap only at the end, so a sheet that
/// is frozen but ungraded cannot hide between two graded ones.
const PAGES: [(&str, &str, usize); 8] = [
    ("chula", "chula.png", 3),
    ("allegretto", "allegretto.png", 3),
    ("batuque", "batuque.png", 3),
    ("carmen", "carmen.png", 5),
    ("cucaracha", "cucaracha.png", 3),
    ("hove", "hove.png", 5),
    ("zizi", "zizi.png", 2),
    ("BachInvention5", "BachInvention5.jpg", 6),
];

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn sha256_hex(bytes: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut padded = bytes.to_vec();
    let bit_len = u64::try_from(bytes.len()).expect("fixture length fits u64") * 8;
    padded.push(0x80);
    while padded.len() % 64 != 56 {
        padded.push(0);
    }
    padded.extend_from_slice(&bit_len.to_be_bytes());
    let mut state = [
        0x6a09e667_u32,
        0xbb67ae85,
        0x3c6ef372,
        0xa54ff53a,
        0x510e527f,
        0x9b05688c,
        0x1f83d9ab,
        0x5be0cd19,
    ];
    for chunk in padded.chunks_exact(64) {
        let mut words = [0_u32; 64];
        for (index, word) in words[..16].iter_mut().enumerate() {
            let offset = index * 4;
            *word = u32::from_be_bytes([
                chunk[offset],
                chunk[offset + 1],
                chunk[offset + 2],
                chunk[offset + 3],
            ]);
        }
        for index in 16..64 {
            let s0 = words[index - 15].rotate_right(7)
                ^ words[index - 15].rotate_right(18)
                ^ (words[index - 15] >> 3);
            let s1 = words[index - 2].rotate_right(17)
                ^ words[index - 2].rotate_right(19)
                ^ (words[index - 2] >> 10);
            words[index] = words[index - 16]
                .wrapping_add(s0)
                .wrapping_add(words[index - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = state;
        for index in 0..64 {
            let sigma1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let choice = (e & f) ^ ((!e) & g);
            let temporary1 = h
                .wrapping_add(sigma1)
                .wrapping_add(choice)
                .wrapping_add(K[index])
                .wrapping_add(words[index]);
            let sigma0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let majority = (a & b) ^ (a & c) ^ (b & c);
            let temporary2 = sigma0.wrapping_add(majority);
            h = g;
            g = f;
            f = e;
            e = d.wrapping_add(temporary1);
            d = c;
            c = b;
            b = a;
            a = temporary1.wrapping_add(temporary2);
        }
        for (slot, value) in state.iter_mut().zip([a, b, c, d, e, f, g, h]) {
            *slot = slot.wrapping_add(value);
        }
    }
    state.iter().map(|word| format!("{word:08x}")).collect()
}

fn txn2_text(family: &str, key: &str) -> String {
    let path = repo_root().join(format!("rust/oracle/stems-beam-txn2-{family}-{key}.txt"));
    std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()))
}

fn row_field<'a>(row: &'a str, name: &str) -> &'a str {
    let mut tokens = row.split(' ');
    while let Some(token) = tokens.next() {
        if token == name {
            return tokens
                .next()
                .unwrap_or_else(|| panic!("field {name} lacks a value: {row}"));
        }
    }
    panic!("row lacks {name}: {row}");
}

fn family_rows<'a>(text: &'a str, family: &str, system_id: usize) -> Vec<&'a str> {
    let marker = format!(" system {system_id} ");
    text.lines()
        .filter(|line| line.split(' ').next() == Some(family) && line.contains(&marker))
        .collect()
}

#[test]
fn second_transaction_replays_through_production_chain() {
    let mut graded = 0;
    let mut saw_missing = false;
    for (key, image, expected_systems) in PAGES {
        let manifest_path =
            repo_root().join(format!("rust/oracle/stems-beam-txn2-manifest-{key}.txt"));
        if !manifest_path.is_file() {
            saw_missing = true;
            continue;
        }
        assert!(
            !saw_missing,
            "installed Boundary-20 corpus has a gap before {key}"
        );
        let manifest = txn2_text("manifest", key);
        let resume_fixture_path =
            repo_root().join(format!("rust/oracle/stems-beam-scheduler-resume-{key}.txt"));
        let resume_bytes = std::fs::read(&resume_fixture_path)
            .unwrap_or_else(|error| panic!("cannot read boundary-19 fixture: {error}"));
        let page_row = manifest
            .lines()
            .find(|line| line.starts_with("stemsbeamtxn2page "))
            .unwrap_or_else(|| panic!("{key}: manifest lacks its page row"));
        assert_eq!(
            row_field(page_row, "schedulerResumeFixtureSha256"),
            sha256_hex(&resume_bytes),
            "{key}: manifest does not pin its exact boundary-19 fixture"
        );
        assert_eq!(
            row_field(page_row, "stop"),
            "SecondTransactionOuterAssignmentComplete"
        );
        assert_eq!(
            row_field(page_row, "systems").parse::<usize>().unwrap(),
            expected_systems
        );

        let base_text = txn2_text("base-apply", key);
        let create_text = txn2_text("create-stem", key);
        let reuse_text = txn2_text("reuse-check", key);
        let flag_text = txn2_text("b-linker-flag", key);
        let sibling_text = txn2_text("sibling-links", key);
        let head_text = txn2_text("head-links", key);
        let outer_text = txn2_text("outer-blinker", key);

        let mut page = b15_hydration::native_predecessor_page(image);
        for index in 0..page.scheduler.systems.len() {
            let scheduler_system = &page.scheduler.systems[index];
            let system_id = scheduler_system.system_id;
            let NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(first) =
                &scheduler_system.status
            else {
                panic!("{key} system {system_id}: prefix lacks its first frontier");
            };
            let completed = NativeStemsBeamCompletedVLinkEvidence {
                plan: first.plan,
                b_linker: first.b_linker,
                v_linker: first.v_linker,
                outer_b_linked_after: true,
                // One frontier advance: no later side consults this
                // transaction's sibling writes.
                sibling_linked_b_linkers: Vec::new(),
            };
            let resume = resume_native_stems_beam_scheduler_after_transaction(
                scheduler_system,
                &page.beam_vlinkers.systems[index],
                &page.beam_builders.systems[index],
                &page.plans.systems[index],
                &completed,
            )
            .unwrap_or_else(|error| panic!("{key} system {system_id}: resume failed: {error}"));
            let NativeStemsBeamSchedulerResumeStatus::AwaitingVLinkTransaction(second) =
                resume.status
            else {
                panic!("{key} system {system_id}: resume did not reach a second frontier");
            };
            // The create-state builder refuses committed prefix deltas; the fast
            // corpus resume adds none, asserted here so a future page cannot
            // silently violate the assumption.
            assert!(
                page.scheduler.systems[index]
                    .deferred_line_deltas
                    .is_empty(),
                "{key} system {system_id}: prefix deltas unsupported at txn2"
            );
            page.scheduler.systems[index].status =
                NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(second);
        }

        for index in 0..page.scheduler.systems.len() {
            let system_id = page.scheduler.systems[index].system_id;
            let NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(second) =
                &page.scheduler.systems[index].status
            else {
                unreachable!();
            };
            let second = second.as_ref().clone();

            // Boundaries 12-15 at the second frontier, through the production
            // applies and the txn2 evidence, exactly as run_real does at the
            // first frontier.
            let hydrated = b15_hydration::run_real_on_page(
                &page,
                system_id,
                &base_text,
                &create_text,
                &reuse_text,
                false,
            )
            .unwrap_or_else(|error| {
                panic!("{key} system {system_id}: txn2 boundary 12-15 replay failed: {error}")
            });
            assert_eq!(hydrated.transaction.key.plan, second.plan);
            assert!(hydrated.transaction.linked_after);
            assert!(!hydrated.transaction.linked_before);
            assert_eq!(hydrated.target, second.b_linker);
            assert_eq!(hydrated.triggering, second.v_linker);

            // Boundary 18 at the second frontier.
            let mut cell = NativeStemsBeamOuterBLinkerCell {
                target_b_linker: hydrated.target,
                linked: hydrated.state_after.linked,
                closed: false,
                committed_by_flag_boundary: hydrated.state_after.committed,
            };
            let facts = hydrated
                .ordered_observers
                .iter()
                .map(|observer| {
                    assert_eq!(
                        *observer, hydrated.triggering,
                        "{key} system {system_id}: non-current observer needs a target fact"
                    );
                    NativeStemsBeamOuterVLinkerFact {
                        v_linker: *observer,
                        has_target_linkers: true,
                    }
                })
                .collect::<Vec<_>>();
            let outer = apply_native_stems_beam_vlink_outer_b_linker_transaction(
                hydrated.transaction.key,
                true,
                hydrated.triggering,
                &facts,
                &mut cell,
            )
            .unwrap_or_else(|error| {
                panic!("{key} system {system_id}: txn2 boundary-18 apply failed: {error}")
            });
            let outer_rows = family_rows(&outer_text, "stemsbeamvlinkouterblinker", system_id);
            assert_eq!(
                outer_rows.len(),
                1,
                "{key} system {system_id}: expected one txn2 outer row"
            );
            let outer_row = outer_rows[0];
            assert_eq!(
                row_field(outer_row, "plan").parse::<usize>().unwrap(),
                second.plan.plan_ordinal
            );
            assert_eq!(row_field(outer_row, "linkedBefore"), "true");
            assert_eq!(
                row_field(outer_row, "valueChanged") == "true",
                outer.linked_value_change_count > 0
            );
            assert_eq!(
                row_field(outer_row, "vSide"),
                match outer.current_v_linker.side {
                    audiveris_omr::stems_step::NativeStemVerticalSide::Top => "TOP",
                    audiveris_omr::stems_step::NativeStemVerticalSide::Bottom => "BOTTOM",
                },
            );
            assert_eq!(outer.linked_write_count, 1);
            assert!(cell.linked);

            // Boundary 16/17 txn2 evidence: pinned by structure now, typed
            // replay owed at the next full checkpoint.
            let flag_targets =
                family_rows(&flag_text, "stemsbeamvlinkblinkerflagtarget", system_id);
            assert_eq!(flag_targets.len(), 1);
            assert_eq!(
                row_field(flag_targets[0], "plan").parse::<usize>().unwrap(),
                second.plan.plan_ordinal
            );
            assert_eq!(row_field(flag_targets[0], "linkedBefore"), "false");
            assert_eq!(row_field(flag_targets[0], "linkedAfter"), "true");
            let head_predecessors =
                family_rows(&head_text, "stemsbeamvlinkheadlinkspredecessor", system_id);
            assert_eq!(head_predecessors.len(), 1);
            let sibling_rows = sibling_text
                .lines()
                .filter(|line| {
                    line.starts_with("stemsbeamvlinksiblinglinks")
                        && line.contains(&format!(" system {system_id} "))
                })
                .count();
            assert_eq!(
                row_field(head_predecessors[0], "b16TransactionRows")
                    .parse::<usize>()
                    .unwrap(),
                sibling_rows,
                "{key} system {system_id}: head predecessor row must pin the sibling bundle"
            );
        }
        graded += 1;
    }
    // Count what is on disk rather than trusting a floor: a gate that grades
    // two sheets of eight would satisfy `>= 2` while quietly ignoring six.
    let installed = PAGES
        .iter()
        .filter(|(key, _, _)| {
            repo_root()
                .join(format!("rust/oracle/stems-beam-txn2-manifest-{key}.txt"))
                .is_file()
        })
        .count();
    assert!(
        installed >= 2,
        "Boundary-20 has only {installed} sheets frozen"
    );
    assert_eq!(
        graded, installed,
        "Boundary-20 graded {graded} of {installed} installed sheets"
    );
}

/// Spike: can the typed chain run the second transaction from the first
/// transaction's carried state, with no second-transaction fixture at all?
///
/// This decides the shape of the remaining STEMS work. The SIDES pass is ~30
/// transactions per system; hydrating each from Java rows costs roughly 276
/// rows and 157KB apiece, so the corpus would need on the order of 100MB of
/// fixtures. If the chain can carry its own state instead, Java evidence
/// becomes a compact per-step oracle and the fixtures collapse by orders of
/// magnitude.
///
/// The state types suggested it should work: `known_canonical_glyphs` is
/// documented as "learned by earlier transactions", `prepare_registration`
/// decides reuse by searching those carried entries rather than reading Java's
/// scan, and `exhaustive_lookup` is optional corroboration that the code clears
/// per transaction.
///
/// **Result: nothing per-transaction is missing. Everything missing is a
/// registry that has not been declared complete.**
///
/// Feeding each blocker in turn and re-running walks through four, in order:
///
/// 1. `MissingLineState` for the new frontier's V linker -- **derivable**. The
///    hydration builds a line state purely from `stored_theoretical_line_before`,
///    `initial_stem_line` and the attachment-alias flag, all typed plan-attempt
///    fields, with no Java row. Seeded here from the plan matrix.
/// 2. `MissingSelectedGlyph` for the plan's pre-existing beam-stump glyph --
///    **page-level identity**. Content comes from the typed attempt; only the
///    Java GlyphIndex id is external, and the probe assigns the canonical alias
///    as `"glyph:" + glyph.getId()`, so alias and id are the same number by
///    construction (85 of 85 certificates across every frozen fixture agree).
/// 3. `AwaitingCompleteGlyphRegistry` -- `prepare_registration` searches
///    `known_canonical_glyphs` by content and only falls back to Java's
///    exhaustive scan when nothing matches. Seeding the registry, not just the
///    binding, gets past it.
/// 4. `AwaitingCompleteSystemStems` -- the same shape one level over, in
///    `known_stems`.
///
/// The two registries differ in what completeness costs, which is the useful
/// part. `systemStems` starts **empty** at STEMS (the frozen create-stem
/// baseline records `systemStems 0`), so a chain that tracks every insertion
/// already holds the whole truth and its absences are proofs. The glyph index
/// does not -- chula starts with 1,650 active glyphs -- so it needs a one-time
/// page-level bootstrap of id and flags, keyed by content.
///
/// So the obstacle was never evidence but *authority*: the model had no way to
/// say "this registry is complete, so absence is proof".
///
/// **It now does, and the chain self-drives.** With the page glyph registry
/// bootstrapped once (`AUDIVERIS_GLYPH_REGISTRY_OUT`, joined by content digest
/// so neither side trusts the other's identities) and `systemStems` declared
/// `CompleteSinceEmptyBaseline`, the second transaction runs on carried state
/// alone and reaches **the same answer Java did**: plan 152, ReuseActive,
/// CreatedChecked. That equivalence is asserted below, because a chain that
/// runs without Java's evidence is only worth having if it agrees with it --
/// otherwise self-drive is just a cheaper way of being wrong.
///
/// The txn2 fixtures are read solely to check the answer; nothing in them
/// feeds the transaction. That is the difference between ~276 rows and 157KB
/// per transaction and one page-level table for a ~30-transaction pass.
#[test]
fn second_transaction_from_carried_state_reproduces_java() {
    let image = "chula.png";
    let key = "chula";
    let system_id = 1;
    let index = 0;

    let page = b15_hydration::native_predecessor_page(image);

    // Transaction 1, hydrated the ordinary way from its frozen fixtures.
    let first = b15_hydration::run_real(
        image,
        system_id,
        &std::fs::read_to_string(
            repo_root().join("rust/oracle/stems-beam-vlink-base-apply-chula.txt"),
        )
        .expect("frozen base-apply"),
        &std::fs::read_to_string(repo_root().join("rust/oracle/stems-beam-create-stem-chula.txt"))
            .expect("frozen create-stem"),
        &std::fs::read_to_string(
            repo_root().join("rust/oracle/stems-beam-vlink-reuse-check-chula.txt"),
        )
        .expect("frozen reuse-check"),
        false,
    )
    .expect("transaction 1 hydrates");

    // The state transaction 1 left behind: glyph registry, allocator, system
    // stems, line states.
    let carried = first.base_apply.state_after.transaction_state.clone();
    println!(
        "carried after txn1: {} known glyphs, {} known stems, union {}",
        carried.glyph_index.known_canonical_glyphs.len(),
        carried.system_stems.known_stems.len(),
        carried.glyph_index.union_size
    );

    // Advance the scheduler to the second frontier.
    let scheduler = {
        let system = &page.scheduler.systems[index];
        let NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(frontier) = &system.status
        else {
            panic!("no first frontier");
        };
        let completed = NativeStemsBeamCompletedVLinkEvidence {
            plan: frontier.plan,
            b_linker: frontier.b_linker,
            v_linker: frontier.v_linker,
            outer_b_linked_after: true,
            sibling_linked_b_linkers: Vec::new(),
        };
        *resume_native_stems_beam_scheduler_after_transaction(
            system,
            &page.beam_vlinkers.systems[index],
            &page.beam_builders.systems[index],
            &page.plans.systems[index],
            &completed,
        )
        .expect("resume to frontier 2")
        .advanced_system
    };
    let NativeStemsBeamSchedulerStatus::AwaitingVLinkTransaction(second) = &scheduler.status else {
        panic!("resume reached no second frontier");
    };
    println!("second frontier plan {}", second.plan.plan_ordinal);

    // Resolve the page-level glyph bootstrap by exact native content. This is
    // the one disclosed input the port still needs because it does not yet own
    // construction of the page-wide GlyphIndex.
    let mut state = carried;
    let attempt = page.plans.systems[index]
        .builders
        .iter()
        .find(|builder| builder.builder_ordinal == second.plan.builder_ordinal)
        .and_then(|builder| {
            builder
                .attempts
                .iter()
                .find(|attempt| attempt.stem_profile == second.plan.stem_profile)
        })
        .expect("second frontier has a plan attempt");
    // Bootstrap the page's glyph registry, the way a self-driving chain would:
    // once per page, from the Java dump, rather than once per transaction from
    // a fixture. The join is by content -- both sides compute the same run
    // digest -- so neither side has to trust the other's identities.
    let registry_text = std::fs::read_to_string(
        repo_root().join("rust/oracle/stems-beam-glyph-registry-chula.txt"),
    )
    .expect("page glyph registry");
    let mut registry = std::collections::BTreeMap::new();
    for line in registry_text.lines() {
        if !line.starts_with("stemsbeamglyphregistryentry ") {
            continue;
        }
        let id = row_field(line, "id").parse::<i32>().expect("registry id");
        let active = row_field(line, "active") == "true";
        registry.insert(row_field(line, "content").to_owned(), (id, active));
    }
    println!("page glyph registry: {} entries", registry.len());

    let identities = attempt
        .glyphs
        .iter()
        .map(|glyph| {
            let key = format!(
                "g:{}:{}:{}:{}:{}",
                glyph.bounds.x,
                glyph.bounds.y,
                glyph.bounds.width,
                glyph.bounds.height,
                b15_hydration::run_table_digest(&glyph.structural_key.run_table),
            );
            let (id, active) = *registry
                .get(&key)
                .unwrap_or_else(|| panic!("plan glyph absent from the page registry: {key}"));
            // The probe assigns the canonical alias as "glyph:" + id, so the
            // alias is the id; nothing extra needs recording.
            (usize::try_from(id).expect("positive glyph id"), id, active)
        })
        .collect::<Vec<_>>();
    println!("plan glyphs resolved against the registry: {identities:?}");
    let bootstrap = attempt
        .glyphs
        .iter()
        .zip(&identities)
        .map(
            |(glyph, (alias, id, active))| NativeStemsBeamGlyphRegistryBootstrapEntry {
                canonical_alias: *alias,
                glyph_id: *id,
                content: NativeStemsBeamFixedGlyphContent {
                    bounds: glyph.bounds,
                    weight: glyph.weight,
                    run_table: glyph.structural_key.run_table.clone(),
                },
                active_in_index: *active,
                // The frozen probe uses EpsilonGC, so registered weak entries are
                // not collected during this chronology.
                strongly_retained: *active,
            },
        )
        .collect::<Vec<_>>();
    let before_prepare = state.clone();
    let authority =
        NativeStemsBeamSystemStemAuthorityProof::from_empty_stems_entry(&state.system_stems, 0)
            .expect("carried systemStems completeness proof");
    let preparation = prepare_native_stems_beam_vlink_frontier_state(
        &scheduler,
        &page.plans.systems[index],
        &mut state,
        &bootstrap,
        authority,
    )
    .expect("prepare carried transaction 2");
    assert_eq!(preparation.plan, second.plan);
    assert_eq!(preparation.v_linker, second.v_linker);
    assert_eq!(preparation.selected_glyphs.len(), 1);
    assert!(preparation.line_state_added);

    // Ambiguous bootstrap evidence is rejected atomically.
    let mut invalid_state = before_prepare.clone();
    let mut ambiguous = bootstrap.clone();
    ambiguous.push(bootstrap[0].clone());
    assert!(
        prepare_native_stems_beam_vlink_frontier_state(
            &scheduler,
            &page.plans.systems[index],
            &mut invalid_state,
            &ambiguous,
            authority,
        )
        .is_err()
    );
    assert_eq!(invalid_state, before_prepare);

    let outcome = apply_native_stems_beam_vlink_create_stem_transaction(
        &scheduler,
        &page.beam_builders.systems[index],
        &page.plans.systems[index],
        &mut state,
        &b15_hydration::checker_context_for_page(&page),
    );

    let transaction = outcome.unwrap_or_else(|error| {
        panic!("self-drive blocked at {error:?} (txn2 fixture inputs deliberately unopened)",)
    });

    // Project B13's actual lazy reads from native head bindings and the
    // persistent S-cell topology. Both plan-152 parents are still unlinked, so
    // Java does not query HeadStem relations and no graph certificate is
    // needed. The page SIG is used only for live head binding validation here;
    // the carried 222/207 mutation state becomes load-bearing in B14.
    let sig = page
        .sig
        .systems
        .iter()
        .find(|sig| sig.system_id == system_id)
        .expect("native system SIG");
    let bindings = page
        .sig
        .bindings
        .iter()
        .find(|bindings| bindings.system_id == system_id)
        .expect("native system bindings");
    let s_cells = initialize_native_stems_beam_s_linker_cells(&page.head_corners.systems[index])
        .expect("native S-cell topology");
    let live = project_native_stems_beam_vlink_reuse_live_state(
        sig,
        bindings,
        &scheduler,
        &page.plans.systems[index],
        &s_cells,
    )
    .expect("native B13 live-state projection");
    let NativeStemsBeamVLinkReuseLiveEvaluation::Entries(entries) = &live.evaluation else {
        panic!("accepted txn2 must inspect relation entries");
    };
    assert_eq!(entries.len(), 2);
    assert!(entries.iter().all(|entry| matches!(
        entry.observation,
        NativeStemsBeamReuseEntryObservation::Examined {
            s_linker_linked: false,
            ..
        }
    )));
    let reuse = evaluate_native_stems_beam_vlink_reuse_check(
        &scheduler,
        &page.plans.systems[index],
        &page.beam_stumps.systems[index],
        &page.beam_vlinkers.systems[index],
        &transaction,
        &state,
        &live,
        first.relation_parameters,
    )
    .expect("native transaction-2 B13");
    assert_eq!(
        reuse.reuse_disposition,
        NativeStemsBeamReuseDisposition::AllUnlinked
    );
    assert!(matches!(
        reuse.outcome,
        NativeStemsBeamVLinkReuseCheckOutcome::ReadyBeforeSigMutation { .. }
    ));

    // The transaction-2 oracle is expected-only: no family file is opened
    // until production B12 and the graph/S-cell-derived B13 have returned.
    let base_text = txn2_text("base-apply", key);
    let create_text = txn2_text("create-stem", key);
    let reuse_text = txn2_text("reuse-check", key);
    assert!(!base_text.is_empty() && !reuse_text.is_empty());

    // The whole point: the answer the chain reached on its own must be the
    // answer Java gave. Anything less would make self-drive a cheaper way of
    // being wrong.
    let row = *family_rows(&create_text, "stemsbeamcreatestemresult", system_id)
        .first()
        .expect("txn2 create fixture has its result row");
    let registration = match transaction.registration.action {
        NativeStemsBeamGlyphRegistrationAction::Reused {
            reinserted_into_active_index: false,
        } => "ReuseActive",
        NativeStemsBeamGlyphRegistrationAction::Reused {
            reinserted_into_active_index: true,
        } => "ReinsertOriginal",
        NativeStemsBeamGlyphRegistrationAction::Registered => "New",
    };
    let disposition = match transaction.disposition {
        NativeStemsBeamCreateStemDisposition::CreatedChecked { .. } => "CreatedChecked",
        NativeStemsBeamCreateStemDisposition::CreatedArtificial { .. } => "CreatedArtificial",
        NativeStemsBeamCreateStemDisposition::Reused { .. } => "Reused",
        NativeStemsBeamCreateStemDisposition::Rejected => "Rejected",
    };
    assert_eq!(
        transaction.plan.plan_ordinal, second.plan.plan_ordinal,
        "self-driven transaction ran a different plan"
    );
    assert_eq!(
        registration,
        row_field(row, "registration"),
        "self-driven registration differs from Java"
    );
    assert_eq!(
        disposition,
        row_field(row, "disposition"),
        "self-driven disposition differs from Java"
    );
    println!(
        "self-drive reproduced Java: plan {} registration {registration} disposition {disposition}",
        transaction.plan.plan_ordinal
    );
}

/// The SIG bootstrap: one ordered snapshot per system determines every incident scan.
///
/// Three boundaries -- base apply, head links and sibling links -- refuse to run
/// without a certificate whose `stem_incident_*` and `beam_incident_*` scans are
/// `edgesOf`, `incomingEdgesOf` and `outgoingEdgesOf` in Java's order. Unlike
/// `systemStems`, the SIG is not empty when STEMS begins, so a chain carrying its own
/// state cannot become authoritative by tracking alone: it has to be told once what is
/// already there. That is the largest of the eight self-drive blockers and is shared by
/// all three.
///
/// What this proves is that being told once is *enough*. JGraphT iterates `vertexSet`
/// and `edgeSet` in insertion order, and a per-vertex incident list is that same order
/// filtered to the vertex -- incoming first, then outgoing, which is exactly what
/// `NativeStemsBeamStemIncidentScanState::ExhaustiveIncomingThenOutgoing` names. So one
/// global ordering determines every incident query, and the bootstrap does not need a
/// per-vertex adjacency dump at all.
///
/// The check is against Java's own recorded scans rather than against a restatement of
/// the rule. Synthetic rows are excluded: only `scope real` describes the actual graph.
#[test]
fn sig_snapshot_derives_the_incident_scans_java_recorded() {
    let snapshot = std::fs::read_to_string(
        repo_root().join("rust/oracle/stems-beam-sig-snapshot-chula-system1.txt"),
    )
    .expect("frozen SIG snapshot");

    let header = snapshot
        .lines()
        .find(|line| line.starts_with("stemsbeamsigsnapshotsystem "))
        .expect("snapshot header");
    let vertex_count: usize = row_field(header, "vertices").parse().expect("vertices");
    let edge_count: usize = row_field(header, "edges").parse().expect("edges");

    let mut vertex_rows = Vec::new();
    let mut edge_rows = Vec::new();
    let mut edges: Vec<(usize, usize)> = Vec::new();
    for line in snapshot.lines() {
        if let Some(rest) = line.strip_prefix("stemsbeamsigsnapshotvertex ") {
            let ordinal: usize = row_field(rest, "ordinal").parse().expect("vertex ordinal");
            assert_eq!(ordinal, vertex_rows.len(), "vertex ordinals must be dense");
            vertex_rows.push(row_after(rest, "row"));
        } else if let Some(rest) = line.strip_prefix("stemsbeamsigsnapshotedge ") {
            let ordinal: usize = row_field(rest, "ordinal").parse().expect("edge ordinal");
            assert_eq!(ordinal, edges.len(), "edge ordinals must be dense");
            edges.push((
                row_field(rest, "source").parse().expect("source"),
                row_field(rest, "target").parse().expect("target"),
            ));
            edge_rows.push(row_after(rest, "row"));
        }
    }
    assert_eq!(vertex_rows.len(), vertex_count, "vertex count");
    assert_eq!(edges.len(), edge_count, "edge count");

    // Recompute the hashes Java wrote, over the same row strings in the same order.
    // A snapshot that parsed cleanly but described a different graph -- reordered,
    // truncated, or from another baseline -- fails here rather than silently
    // producing plausible incident scans.
    let rows_hash = |rows: &[&str]| {
        let mut joined = String::new();
        for row in rows {
            joined.push_str(row);
            joined.push('\n');
        }
        sha256_hex(joined.as_bytes())
    };
    assert_eq!(
        rows_hash(&vertex_rows),
        row_field(header, "vertexHash"),
        "vertex rows do not rebuild Java's ordered vertex hash"
    );
    assert_eq!(
        rows_hash(&edge_rows),
        row_field(header, "edgeHash"),
        "edge rows do not rebuild Java's ordered edge hash"
    );

    // Java's own incident scans, from the frozen base-apply fixture.
    let fixture = std::fs::read_to_string(
        repo_root().join("rust/oracle/stems-beam-vlink-base-apply-chula.txt"),
    )
    .expect("frozen base-apply");
    let mut checked = 0;
    for family in [
        "stemsbeamvlinkbaseapplybeamincident ",
        "stemsbeamvlinkbaseapplystemincident ",
    ] {
        let recorded: Vec<(&str, usize)> = fixture
            .lines()
            .filter_map(|line| line.strip_prefix(family))
            .filter(|rest| {
                row_field(rest, "system") == "1"
                    && row_field(rest, "scope") == "real"
                    && row_field(rest, "phase") == "Before"
            })
            .filter_map(|rest| {
                row_field(rest, "globalRelationIdentity")
                    .strip_prefix("sig-edge:")
                    .map(|ordinal| {
                        (
                            row_field(rest, "direction"),
                            ordinal.parse::<usize>().expect("edge ordinal"),
                        )
                    })
            })
            // An edge at or past the baseline count was added by this transaction, so
            // it is tracked state rather than bootstrap state.
            .filter(|(_, ordinal)| *ordinal < edge_count)
            .collect();
        if recorded.is_empty() {
            // A freshly created stem has no baseline edges at all, so its scan is
            // entirely tracked. That is a real case, not a gap in the snapshot.
            continue;
        }

        // The one vertex every recorded edge touches is the vertex Java scanned.
        let mut candidates: Option<std::collections::BTreeSet<usize>> = None;
        for (_, ordinal) in &recorded {
            let (source, target) = edges[*ordinal];
            let pair = std::collections::BTreeSet::from([source, target]);
            candidates = Some(match candidates {
                None => pair,
                Some(current) => current.intersection(&pair).copied().collect(),
            });
        }
        let candidates = candidates.expect("recorded rows exist");
        assert_eq!(
            candidates.len(),
            1,
            "{family}: recorded edges share no single vertex: {candidates:?}"
        );
        let vertex = *candidates.iter().next().expect("one vertex");

        let derived: Vec<(&str, usize)> = edges
            .iter()
            .enumerate()
            .filter(|(_, (_, target))| *target == vertex)
            .map(|(ordinal, _)| ("Incoming", ordinal))
            .chain(
                edges
                    .iter()
                    .enumerate()
                    .filter(|(_, (source, _))| *source == vertex)
                    .map(|(ordinal, _)| ("Outgoing", ordinal)),
            )
            .collect();
        assert_eq!(
            derived, recorded,
            "{family}: incoming-then-outgoing over the snapshot does not reproduce \
             Java's scan of vertex {vertex}"
        );
        checked += 1;
    }
    assert!(
        checked > 0,
        "no real-scope incident scan was compared; the fixture families moved"
    );
    println!(
        "SIG bootstrap: {vertex_count} vertices, {edge_count} edges; \
         {checked} incident scan(s) derived exactly from insertion order"
    );
}

/// The remainder of a row after `name`, which for the snapshot rows is the exact string
/// Java hashed and therefore must not be re-tokenised.
fn row_after<'a>(row: &'a str, name: &str) -> &'a str {
    let marker = format!(" {name} ");
    let start = row
        .find(&marker)
        .unwrap_or_else(|| panic!("row lacks {name}: {row}"))
        + marker.len();
    &row[start..]
}
